//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.19 at 05:31:49 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://spring_ws.trg/employee", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.employee.schema;
